sudo: false
language: elixir
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.6.6
    - otp_release: 22.0
      elixir: 1.10.1
      env: LATEST=1
env:
  global:
    - MIX_ENV=test
script:
  - if [[ "$LATEST" == "1" ]]; then
      echo "===> Testing with code coverage";
      mix coveralls.travis --trace;
      mix format --check-formatted;
    else
      echo "===> Testing without code coverage";
      mix test --trace;
    fi
